mode: "test"  # or "train"
method: "MC"  # or "mc", "mc_random"

MODEL:
  TRAIN:
    USE_CHECKPOINT : True
  DATA:
    IMG_SIZE: 224
  in_channels: 1
  NUM_CLASSES: 3
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.3
  ATTN_DROP_RATE: 0.3
  DROP_RATE: 0.3
  PRETRAIN_CKPT: "./pretrained_ckpt/epoch_149_loss_0-Copy1.0434.pth"
  SWIN:
    PATCH_SIZE: 4
    APE: False
    IN_CHANS: 3
    MLP_RATIO: 4
    PATCH_NORM: True
    QKV_BIAS: True
    QK_SCALE: null
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [2, 2, 2, 2]
    DECODER_DEPTHS: [2, 2, 2, 1]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    

dae_checkpoint: '../anomaly_label/ablation_noise_dae/best_dae_data_myheart_bound_loss_512_data_augmentation_groupped_delete_circle_swap.pth'
# dae_adv_checkpoint: './dae_saved_models/best_dae_data_myheart_512_adv_penality_augmentation.pth'

# training:
#   data_path: "/optima/exchange/hjebril/plexilite/FAZ/split_dataset/train"
#   modality : ["Images", "masks"]
#   batch_size: 4
#   learning_rate: 0.0005
#   num_epochs: 300

# validation:
#   data_path: "/optima/exchange/hjebril/plexilite/FAZ/split_dataset/valid"
#   modality : ["Images", "masks"]
#   batch_size: 1
#   frequency: 1   # e.g., how often to validate (every epoch, every N steps, etc.)



testing:


  -
    data_path: "/optima/exchange/hjebril/plexilite/FAZ/split_dataset_classification/train"
    modality : ["Images", "masks"]
    output_folder: "./results_dae_stratify/mc/myheart_train"
    batch_size: 1
    save_name: "myheart_train"
    transform: False
 
  -
    data_path: "/optima/exchange/hjebril/plexilite/FAZ/split_dataset_classification/valid"
    modality : ["Images", "masks"]
    output_folder: "./results_dae_stratify/mc/myheart_valid"
    batch_size: 1
    save_name: "myheart_valid"
    transform: False

  -
    data_path: "/optima/exchange/hjebril/plexilite/FAZ/split_dataset_classification/test"
    modality : ["Images", "masks"]
    output_folder: "./results_dae_stratify/mc/myheart_test"
    batch_size: 1
    save_name: "myheart_test"
    transform: False